#!/bin/bash

# Create directory structure
mkdir -p app/core
mkdir -p app/middleware
mkdir -p app/shared
mkdir -p app/api/v1
mkdir -p app/modules/auth/domain
mkdir -p app/modules/auth/infra
mkdir -p frontend/.streamlit
mkdir -p labs
mkdir -p ui/streamlit/pages

# Create main application files
touch app/main.py
touch app/api/v1/router.py
touch app/api/v1/auth.py
if [ ! -f frontend/main.py ]; then
cat > frontend/main.py <<'EOF'
import streamlit as st


st.set_page_config(page_title="FastAPI + Streamlit Starter", page_icon="⚡")
st.title("Streamlit Frontend Bootstrap")
st.write("This file was generated by scripts/init_project.sh. Replace it with your UI.")
EOF
fi

# Create core files
touch app/core/config.py
touch app/core/security.py

# Create middleware files
touch app/middleware/timings.py

# Create shared files
touch app/shared/db.py
touch app/shared/utils.py

# Create auth module files
touch app/modules/auth/schemas.py
touch app/modules/auth/services.py
touch app/modules/auth/deps.py

# Create auth domain files
touch app/modules/auth/domain/models.py
touch app/modules/auth/domain/ports.py

# Create auth infrastructure files
touch app/modules/auth/infra/orm.py
touch app/modules/auth/infra/repositories.py
touch app/modules/auth/infra/token_jwt.py
if [ ! -f frontend/.streamlit/config.toml ]; then
cat > frontend/.streamlit/config.toml <<'EOF'
[server]
headless = true
runOnSave = true
address = "0.0.0.0"
port = 8501
EOF
fi

if [ ! -f labs/README.md ]; then
cat > labs/README.md <<'EOF'
# Labs Workspace

此目錄儲存尚未產品化的實驗專案。建立新 Lab：

# make lab name=example title="Example Lab"

詳情請參考專案 README。
EOF
fi

if [ ! -f ui/streamlit/main.py ]; then
cat > ui/streamlit/main.py <<'EOF'
import streamlit as st

st.set_page_config(page_title="Labs Portal")
st.title("Labs Portal")
st.write("此檔案由 init_project.sh 產生，請以專案中的版本為準。")
EOF
fi

echo "FastAPI project structure created successfully!"
